CREATE SCHEMA IF NOT EXISTS users;

CREATE TABLE users.user (
    id BIGSERIAL PRIMARY KEY,
    user_name VARCHAR(100) NOT NULL,
    cpf VARCHAR(100) NOT NULL,
    adress VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    registration_date TIMESTAMP NOT NULL
);